// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwVenta.Data.Entities.DwVentas;

public partial class DimCustomer
{
    public string CustomerId { get; set; }

    public string ContactName { get; set; }

    public virtual ICollection<FactOrder> FactOrders { get; set; } = new List<FactOrder>();
}