// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwVenta.Data.Entities.Nortwind;

public partial class ClienteAtendidosEmpleado
{
    public int? EmployeeId { get; set; }

    public string Nombre { get; set; }

    public int? ClienteAtendidos { get; set; }
}