// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwVenta.Data.Entities.Nortwind;

public partial class ProductosMasVendidosCategorium
{
    public int CategoryId { get; set; }

    public int? CantidadVendida { get; set; }
}