// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwVenta.Data.Entities.Nortwind;

public partial class VentasCliente
{
    public string CustomerId { get; set; }

    public decimal? Ventas { get; set; }
}