// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


namespace LoadDwVenta.Data.Entities.DwVentas.Configuractions
{
    public partial class DimCustomerConfiguration : IEntityTypeConfiguration<DimCustomer>
    {
        public void Configure(EntityTypeBuilder<DimCustomer> entity)
        {
            entity.HasKey(e => e.CustomerId).HasName("PK_Customers");

            entity.Property(e => e.CustomerId)
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("CustomerID");
            entity.Property(e => e.ContactName).HasMaxLength(30);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimCustomer> entity);
    }
}
