// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LoadDwVenta.Data.Entities.DwVentas.Configuractions
{
    public partial class DimCategoryConfiguration : IEntityTypeConfiguration<DimCategory>
    {
        public void Configure(EntityTypeBuilder<DimCategory> entity)
        {
            entity.HasKey(e => e.CategoryId).HasName("PK_Categories");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(15);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimCategory> entity);
    }
}
