// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


namespace LoadDwVenta.Data.Entities.DwVentas.Configuractions
{
    public partial class DimShipperConfiguration : IEntityTypeConfiguration<DimShipper>
    {
        public void Configure(EntityTypeBuilder<DimShipper> entity)
        {
            entity.HasKey(e => e.ShipperId).HasName("PK_Shippers");

            entity.Property(e => e.ShipperId).HasColumnName("ShipperID");
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.Phone).HasMaxLength(24);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimShipper> entity);
    }
}
